"""add rag knowledge base and file graph tables

Revision ID: 4bd66d500be6
Revises: a79453452d83
Create Date: 2026-05-13 01:42:41.228934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bd66d500be6'
down_revision: Union[str, None] = 'a79453452d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('title', sa.String(length=200), nullable=False, comment='会话标题'),
    sa.Column('user_id', sa.String(length=21), nullable=False, comment='用户ID'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='使用的大模型名称'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活（未关闭）'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注/扩展信息'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversations_is_deleted'), 'chat_conversations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_chat_conversations_user_id'), 'chat_conversations', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('conversation_id', sa.String(length=21), nullable=False, comment='会话ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='消息角色：user/assistant/system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('model_name', sa.String(length=100), nullable=True, comment='该条消息使用的模型'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True, comment='输入token数'),
    sa.Column('completion_tokens', sa.Integer(), nullable=True, comment='输出token数'),
    sa.Column('total_tokens', sa.Integer(), nullable=True, comment='总token数'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_is_deleted'), 'chat_messages', ['is_deleted'], unique=False)
    op.create_table('rag_knowledge_base',
    sa.Column('name', sa.String(length=200), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('kb_type', sa.String(length=20), nullable=True, comment='类型: user/demo'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_rag_knowledge_base_is_deleted'), 'rag_knowledge_base', ['is_deleted'], unique=False)
    op.create_table('rag_knowledge_base_file',
    sa.Column('kb_id', sa.String(length=21), nullable=False, comment='所属知识库'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('content', sa.Text(), nullable=False, comment='文本内容'),
    sa.Column('file_type', sa.String(length=20), nullable=True, comment='文件类型'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小(字节)'),
    sa.Column('schema_json', sa.JSON(), nullable=True, comment='该文件的自定义Schema定义'),
    sa.Column('has_graph', sa.Boolean(), nullable=True, comment='是否已构建图谱'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.ForeignKeyConstraint(['kb_id'], ['rag_knowledge_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_knowledge_base_file_is_deleted'), 'rag_knowledge_base_file', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_file_kb_id'), 'rag_knowledge_base_file', ['kb_id'], unique=False)
    op.create_table('rag_knowledge_graph',
    sa.Column('file_id', sa.String(length=21), nullable=False, comment='所属文件'),
    sa.Column('graph_data', sa.JSON(), nullable=True, comment='图谱结构数据(节点+边)'),
    sa.Column('chunks_data', sa.JSON(), nullable=True, comment='文本块数据 {chunk_id: text}'),
    sa.Column('built_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='构建时间'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.ForeignKeyConstraint(['file_id'], ['rag_knowledge_base_file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index(op.f('ix_rag_knowledge_graph_is_deleted'), 'rag_knowledge_graph', ['is_deleted'], unique=False)
    op.drop_index(op.f('ix_demos_is_deleted'), table_name='demos')
    op.drop_table('demos')
    op.drop_index(op.f('ix_demo_cache_is_deleted'), table_name='demo_cache')
    op.drop_index(op.f('ix_demo_cache_title'), table_name='demo_cache')
    op.drop_table('demo_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_cache',
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='标题'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True, comment='内容'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否激活'),
    sa.Column('id', sa.VARCHAR(length=21), autoincrement=False, nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id', name=op.f('demo_cache_pkey'))
    )
    op.create_index(op.f('ix_demo_cache_title'), 'demo_cache', ['title'], unique=False)
    op.create_index(op.f('ix_demo_cache_is_deleted'), 'demo_cache', ['is_deleted'], unique=False)
    op.create_table('demos',
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='标题'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True, comment='内容'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否激活'),
    sa.Column('id', sa.VARCHAR(length=21), autoincrement=False, nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id', name=op.f('demos_pkey'))
    )
    op.create_index(op.f('ix_demos_is_deleted'), 'demos', ['is_deleted'], unique=False)
    op.drop_index(op.f('ix_rag_knowledge_graph_is_deleted'), table_name='rag_knowledge_graph')
    op.drop_table('rag_knowledge_graph')
    op.drop_index(op.f('ix_rag_knowledge_base_file_kb_id'), table_name='rag_knowledge_base_file')
    op.drop_index(op.f('ix_rag_knowledge_base_file_is_deleted'), table_name='rag_knowledge_base_file')
    op.drop_table('rag_knowledge_base_file')
    op.drop_index(op.f('ix_rag_knowledge_base_is_deleted'), table_name='rag_knowledge_base')
    op.drop_table('rag_knowledge_base')
    op.drop_index(op.f('ix_chat_messages_is_deleted'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_conversations_user_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_is_deleted'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
