"""add knowledge base role permission table

Revision ID: 69e2fb1ff1cc
Revises: 4bd66d500be6
Create Date: 2026-05-15 15:42:26.492766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e2fb1ff1cc'
down_revision: Union[str, None] = '4bd66d500be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_knowledge_base_role',
    sa.Column('role_id', sa.String(length=21), nullable=False, comment='角色ID'),
    sa.Column('kb_id', sa.String(length=21), nullable=False, comment='知识库ID'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.ForeignKeyConstraint(['kb_id'], ['rag_knowledge_base.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['core_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'kb_id', name='uq_role_kb')
    )
    op.create_index(op.f('ix_rag_knowledge_base_role_is_deleted'), 'rag_knowledge_base_role', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_role_kb_id'), 'rag_knowledge_base_role', ['kb_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_role_role_id'), 'rag_knowledge_base_role', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_knowledge_base_role_role_id'), table_name='rag_knowledge_base_role')
    op.drop_index(op.f('ix_rag_knowledge_base_role_kb_id'), table_name='rag_knowledge_base_role')
    op.drop_index(op.f('ix_rag_knowledge_base_role_is_deleted'), table_name='rag_knowledge_base_role')
    op.drop_table('rag_knowledge_base_role')
    # ### end Alembic commands ###
